name: Main testing workflow
on: [pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v4
    - name: Test GitHub Action
      uses: ./
      with:
        git_path: https://github.com/urlstechie/urlchecker-test-repo
        subfolder: test_action
        file_types: .md,.py,.rst
        timeout: 5
        retry_count: 3
        exclude_urls: https://github.com/SuperKogito/URLs-checker/issues/1,https://github.com/SuperKogito/URLs-checker/issues/2
        exclude_patterns: https://github.com/SuperKogito/Voice-based-gender-recognition/issues
        exclude_files: README.md,/github/workspace/_config.yml

    - name: Test UrlChecker Action with Save
      uses: ./
      with:
        git_path: https://github.com/urlstechie/urlchecker-test-repo
        subfolder: test_action
        file_types: .md
        force_pass: true
        save: results.csv
    - name: Check that results exist
      run: cat results.csv
    - name: Upload check results
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: urlchecker-results
        path: results.csv
